// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPI.Model;

namespace WebAPI.Model.Migrations
{
    [DbContext(typeof(EzBetDbContext))]
    [Migration("20191026102737_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WebAPI.Model.Entities.Bet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GameID");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<string>("Score");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.ToTable("bet");
                });

            modelBuilder.Entity("WebAPI.Model.Entities.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BetEndDate");

                    b.Property<DateTime>("BetStartDate");

                    b.Property<string>("GameState")
                        .HasMaxLength(16);

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.HasKey("ID");

                    b.ToTable("game");
                });

            modelBuilder.Entity("WebAPI.Model.Entities.Bet", b =>
                {
                    b.HasOne("WebAPI.Model.Entities.Game")
                        .WithMany("Bets")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
